{application,rebar_bug,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{rebar_bug_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[rebar_bug_app,rebar_bug_sup,sample]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
